### ISSUE TITLE
PatCID database

### ISSUE THREAD

**Issue by ByteTora** [DS4SD/PatCID#1]
Hi Lucas,
 your work is truly impeccable! I have successfully run the script of __"Search PatCID with Molecule Query"__ and __"Search PatCID with Patent Query"__ locally, and they are very user-friendly! 

I currently have a question: how do I build a **PatCID database**, specifically the __[jsonl file](https://doi.org/10.5281/zenodo.10572870)__ , since **my patent data is not within PatCID**. Thank you🥰!

**Comment by lucas-morin** [comment]
Hello @ByteTora,

Thanks for your positive feedback! 

To build a PatCID dataset yourself on new patent documents, you currently need to:
- Run the different components of the document ingestion pipeline: (1) [segmentation](https://github.com/Kohulan/DECIMER-Image-Segmentation) (DECIMER-Segmentation), (2) [classification](https://github.com/DS4SD/MolClassifier), and (3) [recognition](https://github.com/DS4SD/MolGrapher); by following the instructions from the three repositories,
- Format the output to match the [PatCID jsonl file format](https://zenodo.org/records/10572870). 

Best,
Lucas

**Comment by ByteTora** [comment]
Thank you for your valuable feedback. It has been duly noted and appreciated.🥰
