### ISSUE TITLE
About the implementation of Substructure and Similarity Search

### ISSUE THREAD

**Issue by lannester666** [DS4SD/PatCID#3]
Thank you for your great work! I have a question about that in the paper and demo video, I can see that the system can support not only the specific molecule search, but also the Substructure and Similarity Search. But in the paper, I understand that you are using the inchi key to search and get the molecule search result, but how to do the Substructure and Similarity Search? Do you use another metric or anything else? I didn't find the method in the paper and the supplementary materials and I'm curious about how to do that

**Comment by lucas-morin** [comment]
Hello @lannester666,

Thanks for your interest in PatCID!
As you noted, for **identity search**, we use the InChIKey string match.
For **similarity search**, we convert molecules into [RDKit Daylight fingerprints](https://www.rdkit.org/docs/RDKit_Book.html) and store these fingerprints in a vector database ([Milvus](https://milvus.io/)). Similarity is then computed using the Tanimoto score. 
For **substructure search**, we follow the same approach. We use Milvus to do a first filtering, by searching fingerprints having a specific query pattern. On the filtered set, we use RDKit to get exact substructures.
This approach allows to leverage the efficient retrieval capabilities of a vector database.

**Comment by lannester666** [comment]
Thank you for your detailed response！
